.TH MYFILEWRITE 3 "21-Sep-2025" "v1.0 OS Assignment" "User Commands"
.SH NAME
myfilewrite \- write data to a file
.SH SYNOPSIS
.B myfilewrite
.RI FILE DATA
.SH DESCRIPTION
.B myfilewrite
writes the string DATA to the specified FILE pointer. 
Returns the number of bytes written or -1 on error.
.SH AUTHOR
Fatima (BSDSF23M020) <fatimatuzahra355@gmail.com>
