.TH MYFILECLOSE 3 "21-Sep-2025" "v1.0 OS Assignment" "User Commands"
.SH NAME
myfileclose \- close an opened file
.SH SYNOPSIS
.B myfileclose
.RI FILE
.SH DESCRIPTION
.B myfileclose
closes the specified FILE pointer. Returns 0 on success and EOF (-1) on failure.
.SH AUTHOR
Fatima (BSDSF23M020) <fatimatuzahra355@gmail.com>
