.TH MYSTRCOPY 3 "21-Sep-2025" "v1.0 OS Assignment" "User Commands"
.SH NAME
mystrcopy \- copy a string to another string
.SH SYNOPSIS
.B mystrcopy
.RI DEST SRC
.SH DESCRIPTION
.B mystrcopy
copies the contents of the source string (SRC) into the destination string (DEST).
The destination must have enough space to store the source string including the null terminator.
.SH AUTHOR
Fatima (BSDSF23M020) <fatimatuzahra355@gmail.com>
