.TH MYCAT 1 "21-Sep-2025" "v1.0 OS Assignment" "User Commands"
.SH NAME
mycat \- display contents of a file
.SH SYNOPSIS
.B mycat
.RI FILE...
.SH DESCRIPTION
.B mycat
reads the contents of the specified file(s) and prints them to standard output. 
It mimics the behavior of the UNIX 'cat' command.
.SH AUTHOR
Fatima (BSDSF23M020) <fatimatuzahra355@gmail.com>
