.TH MYFILEOPEN 1 "21-Sep-2025" "v1.0 OS Assignment" "User Commands"
.SH NAME
myfileopen \- open a file for reading or writing
.SH SYNOPSIS
.B myfileopen
.RI FILENAME MODE
.SH DESCRIPTION
.B myfileopen
opens a file with the specified FILENAME and MODE ("r" for read, "w" for write, etc.).
Returns a FILE pointer on success or NULL on failure.
.SH AUTHOR
Fatima (BSDSF23M020) <fatimatuzahra355@gmail.com>
